### PR TITLE
client: improve implementation of CPU throttling

### LINKED ISSUE #5231: Setting preference "Use at most N % CPU time" during operation does not work reliably
**Describe the bug**
When setting "Use at most N % CPU time" back and forth during BOINC (projects) running, it doesn't seem to pick up reliably. Sometimes, you can see CPU usage go up/down, often it does not work unless BOINC is restarted. 

**Steps To Reproduce**
1.    Set <cpu_usage_limit>0.010000</cpu_usage_limit> and <niu_cpu_usage_limit>0.010000</niu_cpu_usage_limit> in file global_prefs_override.xml
2. Start up BOINC
3. Monitor CPU usage via task manager, resource monitor or the like
4. Switch "Use at most N % CPU time" to 100%
5. Watch CPU usage go up in your monitoring software
6. Switch "Use at most N % CPU time" back to 0.01%
7. Watch CPU usage **stay up** in your monitoring software
8. Repeat 4-7. It will eventually fail often/most of the time
9. Restart BOINC and see the setting being picked up well again

**Expected behavior**
Setting the CPU usage limit should pick up right away. (Especially when using GUI RPC, which is my use case)

**Screenshots**
grafik

**System Information**
 - OS: Windows 11 22H2 / Microsoft Windows [Version 10.0.22621.1635]
 - BOINC Version: 7.22.1 (x64) and 7.20.2 (x64)

**Additional context**
- Message board thread regarding that topic: https://boinc.berkeley.edu/forum_thread.php?id=14981
- Logs (with debug flags cpu_sched, cpu_sched_debug, cpu_sched_status, priority_debug enabled): 

> 09.05.2023 20:21:24 |  | Starting BOINC client version 7.22.1 for windows_x86_64
> 09.05.2023 20:21:24 |  | log flags: file_xfer, sched_ops, task, cpu_sched, cpu_sched_debug, cpu_sched_status
> 09.05.2023 20:21:24 |  | log flags: priority_debug
> 09.05.2023 20:21:24 |  | Libraries: libcurl/8.0.1-DEV Schannel zlib/1.2.13
> 09.05.2023 20:21:24 |  | Data directory: D:\ProgramData\BOINC
> 09.05.2023 20:21:24 |  | Running under account Alex
> 09.05.2023 20:21:24 |  | OpenCL: AMD/ATI GPU 0: Radeon RX 580 Series (driver version 3516.0 (PAL,HSAIL), device version OpenCL 2.0 AMD-APP (3516.0), 8192MB, 8192MB available, 6295 GFLOPS peak)
> 09.05.2023 20:21:29 |  | Windows processor group 0: 12 processors
> 09.05.2023 20:21:29 |  | Host name: DESKTOP-DEB0MS8
> 09.05.2023 20:21:29 |  | Processor: 12 GenuineIntel Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz [Family 6 Model 165 Stepping 3]
> 09.05.2023 20:21:29 |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss htt tm pni ssse3 fma cx16 sse4_1 sse4_2 movebe popcnt aes f16c rdrandsyscall nx lm avx avx2 tm2 pbe fsgsbase bmi1 smep bmi2
> 09.05.2023 20:21:29 |  | OS: Microsoft Windows 11: Professional x64 Edition, (10.00.22621.00)
> 09.05.2023 20:21:29 |  | Memory: 31.91 GB physical, 38.66 GB virtual
> 09.05.2023 20:21:29 |  | Disk: 434.44 GB total, 276.77 GB free
> 09.05.2023 20:21:29 |  | Local time is UTC +2 hours
> 09.05.2023 20:21:29 |  | No WSL found.
> 09.05.2023 20:21:29 |  | Config: GUI RPCs allowed from:
> 09.05.2023 20:21:29 |  | 192.168.178.2
> 09.05.2023 20:21:29 |  | 127.0.0.1
> 09.05.2023 20:21:29 |  | Config: don't compute while Back4Blood.exe is running
> 09.05.2023 20:21:29 |  | Config: don't compute while DOOMEternalx64vk.exe is running
> 09.05.2023 20:21:29 |  | Config: don't compute while RocketLeague.exe is running
> 09.05.2023 20:21:29 |  | Config: don't compute while starwarssquadrons.exe is running
> 09.05.2023 20:21:29 |  | Config: don't compute while starwarssquadrons_launcher.exe is running
> 09.05.2023 20:21:29 | World Community Grid | General prefs: from World Community Grid (last modified 03-Apr-2023 11:14:37)
> 09.05.2023 20:21:29 | World Community Grid | Computer location: home
> 09.05.2023 20:21:29 | World Community Grid | General prefs: no separate prefs for home; using your defaults
> 09.05.2023 20:21:29 |  | Reading preferences override file
> 09.05.2023 20:21:30 |  | Preferences:
> 09.05.2023 20:21:30 |  | -  When computer is in use
> 09.05.2023 20:21:30 |  | -     'In use' means mouse/keyboard input in last 3.0 minutes
> 09.05.2023 20:21:30 |  | -     don't use GPU
> 09.05.2023 20:21:30 |  | -     max CPUs used: 12
> 09.05.2023 20:21:30 |  | -     Use at most 0% of the CPU time
> 09.05.2023 20:21:30 |  | -     suspend if non-BOINC CPU load exceeds 50%
> 09.05.2023 20:21:30 |  | -     max memory usage: 15.96 GB
> 09.05.2023 20:21:30 |  | -  When computer is not in use
> 09.05.2023 20:21:30 |  | -     max CPUs used: 12
> 09.05.2023 20:21:30 |  | -     Use at most 0% of the CPU time
> 09.05.2023 20:21:30 |  | -     suspend if non-BOINC CPU load exceeds 50%
> 09.05.2023 20:21:30 |  | -     max memory usage: 23.93 GB
> 09.05.2023 20:21:30 |  | -  Suspend if running on batteries
> 09.05.2023 20:21:30 |  | -  Leave apps in memory if not running
> 09.05.2023 20:21:30 |  | -  Store at least 0.20 days of work
> 09.05.2023 20:21:30 |  | -  Store up to an additional 0.30 days of work
> 09.05.2023 20:21:30 |  | -  max disk usage: 10.00 GB
> 09.05.2023 20:21:30 |  | -  (to change preferences, visit a project web site or select Preferences in the Manager)
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] Request CPU reschedule: Prefs update
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] Request CPU reschedule: Startup
> 09.05.2023 20:21:30 |  | Setting up project and slot directories
> 09.05.2023 20:21:30 |  | Checking active tasks
> 09.05.2023 20:21:30 | yoyo@home | Task que_N_27_D_7_429141200_429141399_1683184524_433_1 is 0.28 days overdue; you may not get credit for it.  Consider aborting it.
> 09.05.2023 20:21:30 |  | Using account manager BOINCstatsBAM!
> 09.05.2023 20:21:30 | https://boinc.thesonntags.com/collatz/ | URL https://boinc.thesonntags.com/collatz/; Computer ID not assigned yet; resource share 100
> 09.05.2023 20:21:30 | http://setiathome.berkeley.edu/ | URL http://setiathome.berkeley.edu/; Computer ID not assigned yet; resource share 100
> 09.05.2023 20:21:30 | climateprediction.net | URL https://climateprediction.net/; Computer ID 1524883; resource share 0
> 09.05.2023 20:21:30 | Einstein@Home | URL https://einstein.phys.uwm.edu/; Computer ID 13133942; resource share 0
> 09.05.2023 20:21:30 | GPUGRID | URL https://www.gpugrid.net/; Computer ID 606025; resource share 0
> 09.05.2023 20:21:30 | Rosetta@home | URL https://boinc.bakerlab.org/rosetta/; Computer ID 5895337; resource share 0
> 09.05.2023 20:21:30 | World Community Grid | URL http://www.worldcommunitygrid.org/; Computer ID 8699617; resource share 100
> 09.05.2023 20:21:30 | World Community Grid | Not using AMD/ATI GPU: project preferences
> 09.05.2023 20:21:30 | WUProp@Home | URL https://wuprop.boinc-af.org/; Computer ID 269383; resource share 100
> 09.05.2023 20:21:30 | yoyo@home | URL http://www.rechenkraft.net/yoyo/; Computer ID 518434; resource share 0
> 09.05.2023 20:21:30 |  | Setting up GUI RPC socket
> 09.05.2023 20:21:30 |  | Checking presence of 269 project files
> 09.05.2023 20:21:30 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.897158
> 09.05.2023 20:21:30 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.897158
> 09.05.2023 20:21:30 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.897158
> 09.05.2023 20:21:30 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9228.070373 rs 9582.897158
> 09.05.2023 20:21:30 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.897158
> 09.05.2023 20:21:30 | World Community Grid | [prio] -0.027631 rsf 1.000000 rt 264.787539 rs 9582.897158
> 09.05.2023 20:21:30 | yoyo@home | [prio] -1000.009396 rsf 0.000000 rt 90.039246 rs 9582.897158
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] Request CPU reschedule: Not idle
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] Request CPU reschedule: periodic CPU scheduling
> 09.05.2023 20:21:30 | https://boinc.thesonntags.com/collatz/ | [prio] recent est credit: 0.00G in 5.93 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:21:30 | http://setiathome.berkeley.edu/ | [prio] recent est credit: 0.00G in 5.93 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:21:30 | climateprediction.net | [prio] recent est credit: 0.00G in 5.93 sec, 0.000032 + -0.000000 ->0.000032
> 09.05.2023 20:21:30 | Einstein@Home | [prio] recent est credit: 0.00G in 5.93 sec, 9228.070373 + -0.151860 ->9227.918513
> 09.05.2023 20:21:30 | GPUGRID | [prio] recent est credit: 0.00G in 5.93 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:21:30 | Rosetta@home | [prio] recent est credit: 0.00G in 5.93 sec, 29.572564 + -0.000487 ->29.572077
> 09.05.2023 20:21:30 | World Community Grid | [prio] recent est credit: 0.00G in 5.93 sec, 264.787539 + -0.004357 ->264.783182
> 09.05.2023 20:21:30 | WUProp@Home | [prio] recent est credit: 0.00G in 5.93 sec, 0.001709 + -0.000000 ->0.001709
> 09.05.2023 20:21:30 | yoyo@home | [prio] recent est credit: 0.00G in 5.93 sec, 90.039246 + -0.001482 ->90.037764
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] schedule_cpus(): start
> 09.05.2023 20:21:30 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9227.918513 rs 9582.739459
> 09.05.2023 20:21:30 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | World Community Grid | [prio] -0.027631 rsf 1.000000 rt 264.783182 rs 9582.739459
> 09.05.2023 20:21:30 | yoyo@home | [prio] -1000.009396 rsf 0.000000 rt 90.037764 rs 9582.739459
> 09.05.2023 20:21:30 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9227.918513 rs 9582.739459
> 09.05.2023 20:21:30 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:21:30 | World Community Grid | [prio] -0.027631 rsf 1.000000 rt 264.783182 rs 9582.739459
> 09.05.2023 20:21:30 | yoyo@home | [prio] -1000.009396 rsf 0.000000 rt 90.037764 rs 9582.739459
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] reserving 1.000000 of coproc ATI
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (AMD/ATI GPU, FIFO) (prio -1000.962973)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] add to run list: que_N_27_D_7_429141200_429141399_1683184524_433_1 (CPU, EDF) (prio -1000.009396)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] add to run list: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (CPU, EDF) (prio -1000.009550)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] add to run list: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (CPU, EDF) (prio -1000.009703)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2976_0 (CPU, FIFO) (prio -0.027631)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2959_0 (CPU, FIFO) (prio -0.027785)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198501_2359_1 (CPU, FIFO) (prio -0.027939)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2962_0 (CPU, FIFO) (prio -0.028093)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198501_2392_1 (CPU, FIFO) (prio -0.028246)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2972_0 (CPU, FIFO) (prio -0.028400)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2978_1 (CPU, FIFO) (prio -0.028554)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (CPU, FIFO) (prio -1001.002933)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (CPU, FIFO) (prio -1001.003087)
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] enforce_run_list(): start
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] preliminary job list:
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] 0: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] 1: que_N_27_D_7_429141200_429141399_1683184524_433_1 (MD: yes; UTS: no)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] 2: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (MD: yes; UTS: no)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] 3: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (MD: yes; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 4: MCM1_0198504_2976_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 5: MCM1_0198504_2959_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 6: MCM1_0198501_2359_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 7: MCM1_0198504_2962_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 8: MCM1_0198501_2392_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 9: MCM1_0198504_2972_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 10: MCM1_0198504_2978_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] 11: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] 12: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] final job list:
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] 0: que_N_27_D_7_429141200_429141399_1683184524_433_1 (MD: yes; UTS: no)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] 1: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (MD: yes; UTS: no)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] 2: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (MD: yes; UTS: no)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] 3: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 4: MCM1_0198504_2976_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 5: MCM1_0198504_2959_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 6: MCM1_0198501_2359_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 7: MCM1_0198504_2962_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 8: MCM1_0198501_2392_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 9: MCM1_0198504_2972_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] 10: MCM1_0198504_2978_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] 11: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] 12: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (MD: no; UTS: no)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] scheduling que_N_27_D_7_429141200_429141399_1683184524_433_1 (high priority)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] scheduling ecm_ru_1683140721_10_469M.c282_2518_P1_0 (high priority)
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched_debug] scheduling ecm_ru_1683590148_10_1104.c217_7391_P1_0 (high priority)
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] scheduling h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2976_0
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2959_0
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198501_2359_1
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2962_0
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198501_2392_1
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2972_0
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2978_1
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] scheduling h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched_debug] scheduling h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched] Restarting task h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 using einstein_O3MD1 version 103 (GW-SSE2) in slot 10
> 09.05.2023 20:21:30 | Einstein@Home | [css] running h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 ()
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched] Restarting task ecm_ru_1683140721_10_469M.c282_2518_P1_0 using ecm version 70502 in slot 0
> 09.05.2023 20:21:30 | yoyo@home | [css] running ecm_ru_1683140721_10_469M.c282_2518_P1_0 ()
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched] Restarting task que_N_27_D_7_429141200_429141399_1683184524_433_1 using m-queens version 1 in slot 1
> 09.05.2023 20:21:30 | yoyo@home | [css] running que_N_27_D_7_429141200_429141399_1683184524_433_1 ()
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched] Restarting task h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 using einstein_O3MD1 version 103 (GW-SSE2) in slot 2
> 09.05.2023 20:21:30 | Einstein@Home | [css] running h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 ()
> 09.05.2023 20:21:30 | yoyo@home | [cpu_sched] Restarting task ecm_ru_1683590148_10_1104.c217_7391_P1_0 using ecm version 70502 in slot 11
> 09.05.2023 20:21:30 | yoyo@home | [css] running ecm_ru_1683590148_10_1104.c217_7391_P1_0 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198504_2976_0 using mcm1 version 761 in slot 8
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198504_2976_0 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198504_2959_0 using mcm1 version 761 in slot 12
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198504_2959_0 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198501_2359_1 using mcm1 version 761 in slot 13
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198501_2359_1 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198504_2962_0 using mcm1 version 761 in slot 4
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198504_2962_0 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198501_2392_1 using mcm1 version 761 in slot 14
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198501_2392_1 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198504_2972_0 using mcm1 version 761 in slot 15
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198504_2972_0 ()
> 09.05.2023 20:21:30 | World Community Grid | [cpu_sched] Restarting task MCM1_0198504_2978_1 using mcm1 version 761 in slot 16
> 09.05.2023 20:21:30 | World Community Grid | [css] running MCM1_0198504_2978_1 ()
> 09.05.2023 20:21:30 | Einstein@Home | [cpu_sched] Restarting task h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 using einstein_O3MDF version 103 (GW-opencl-ati) in slot 7
> 09.05.2023 20:21:30 | Einstein@Home | [css] running h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 ()
> 09.05.2023 20:21:30 | WUProp@Home | [cpu_sched] Restarting task data_collect_v4_1683401806_231083_0 using data_collect_v4 version 430 (nci) in slot 6
> 09.05.2023 20:21:30 | WUProp@Home | [css] running data_collect_v4_1683401806_231083_0 ()
> 09.05.2023 20:21:30 |  | [cpu_sched_debug] enforce_run_list: end
> 09.05.2023 20:21:30 | https://boinc.thesonntags.com/collatz/ | Fetching scheduler list
> 09.05.2023 20:21:54 |  | Project communication failed: attempting access to reference site
> 09.05.2023 20:21:55 |  | Internet access OK - project servers may be temporarily down.
> 09.05.2023 20:21:57 | http://setiathome.berkeley.edu/ | Fetching scheduler list
> 09.05.2023 20:21:59 | http://setiathome.berkeley.edu/ | Master file download succeeded
> 09.05.2023 20:22:04 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:22:04 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:22:04 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:22:04 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9227.918513 rs 9582.739459
> 09.05.2023 20:22:04 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:22:04 | World Community Grid | [prio] -0.027631 rsf 1.000000 rt 264.783182 rs 9582.739459
> 09.05.2023 20:22:04 | yoyo@home | [prio] -1000.009396 rsf 0.000000 rt 90.037764 rs 9582.739459
> 09.05.2023 20:22:04 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 0.500000 rt 0.000000 rs 9612.311568
> 09.05.2023 20:22:04 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 0.500000 rt 0.000000 rs 9612.311568
> 09.05.2023 20:22:04 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9612.311568
> 09.05.2023 20:22:04 | Einstein@Home | [prio] -1000.960010 rsf 0.000000 rt 9227.918513 rs 9612.311568
> 09.05.2023 20:22:04 | Rosetta@home | [prio] -1000.003076 rsf 0.000000 rt 29.572077 rs 9612.311568
> 09.05.2023 20:22:04 | World Community Grid | [prio] -0.055093 rsf 0.500000 rt 264.783182 rs 9612.311568
> 09.05.2023 20:22:04 | yoyo@home | [prio] -1000.009367 rsf 0.000000 rt 90.037764 rs 9612.311568
> 09.05.2023 20:22:05 | http://setiathome.berkeley.edu/ | Sending scheduler request: To fetch work.
> 09.05.2023 20:22:05 | http://setiathome.berkeley.edu/ | Requesting new tasks for CPU and AMD/ATI GPU
> 09.05.2023 20:22:07 | http://setiathome.berkeley.edu/ | Scheduler request failed: HTTP file not found
> 09.05.2023 20:22:12 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:22:12 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9582.739459
> 09.05.2023 20:22:12 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9582.739459
> 09.05.2023 20:22:12 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9227.918513 rs 9582.739459
> 09.05.2023 20:22:12 | Rosetta@home | [prio] -1000.003086 rsf 0.000000 rt 29.572077 rs 9582.739459
> 09.05.2023 20:22:12 | World Community Grid | [prio] -0.027631 rsf 1.000000 rt 264.783182 rs 9582.739459
> 09.05.2023 20:22:12 | yoyo@home | [prio] -1000.009396 rsf 0.000000 rt 90.037764 rs 9582.739459
> 09.05.2023 20:22:12 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9612.311568
> 09.05.2023 20:22:12 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9612.311568
> 09.05.2023 20:22:12 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9612.311568
> 09.05.2023 20:22:12 | Einstein@Home | [prio] -1000.960010 rsf 0.000000 rt 9227.918513 rs 9612.311568
> 09.05.2023 20:22:12 | Rosetta@home | [prio] -1000.003076 rsf 0.000000 rt 29.572077 rs 9612.311568
> 09.05.2023 20:22:12 | World Community Grid | [prio] -0.027546 rsf 1.000000 rt 264.783182 rs 9612.311568
> 09.05.2023 20:22:12 | yoyo@home | [prio] -1000.009367 rsf 0.000000 rt 90.037764 rs 9612.311568
> 09.05.2023 20:22:15 | World Community Grid | General prefs: from World Community Grid (last modified 03-Apr-2023 11:14:37)
> 09.05.2023 20:22:15 | World Community Grid | Computer location: home
> 09.05.2023 20:22:15 | World Community Grid | General prefs: no separate prefs for home; using your defaults
> 09.05.2023 20:22:15 |  | Reading preferences override file
> 09.05.2023 20:22:16 |  | Preferences:
> 09.05.2023 20:22:16 |  | -  When computer is in use
> 09.05.2023 20:22:16 |  | -     'In use' means mouse/keyboard input in last 3.0 minutes
> 09.05.2023 20:22:16 |  | -     don't use GPU
> 09.05.2023 20:22:16 |  | -     max CPUs used: 12
> 09.05.2023 20:22:16 |  | -     Use at most 100% of the CPU time
> 09.05.2023 20:22:16 |  | -     suspend if non-BOINC CPU load exceeds 50%
> 09.05.2023 20:22:16 |  | -     max memory usage: 15.96 GB
> 09.05.2023 20:22:16 |  | -  When computer is not in use
> 09.05.2023 20:22:16 |  | -     max CPUs used: 12
> 09.05.2023 20:22:16 |  | -     Use at most 100% of the CPU time
> 09.05.2023 20:22:16 |  | -     suspend if non-BOINC CPU load exceeds 50%
> 09.05.2023 20:22:16 |  | -     max memory usage: 23.93 GB
> 09.05.2023 20:22:16 |  | -  Suspend if running on batteries
> 09.05.2023 20:22:16 |  | -  Leave apps in memory if not running
> 09.05.2023 20:22:16 |  | -  Store at least 0.20 days of work
> 09.05.2023 20:22:16 |  | -  Store up to an additional 0.30 days of work
> 09.05.2023 20:22:16 |  | -  max disk usage: 10.00 GB
> 09.05.2023 20:22:16 |  | -  (to change preferences, visit a project web site or select Preferences in the Manager)
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] Request CPU reschedule: Prefs update
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] Request CPU reschedule: Preferences override
> 09.05.2023 20:22:16 | https://boinc.thesonntags.com/collatz/ | [prio] recent est credit: 0.00G in 45.42 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:22:16 | http://setiathome.berkeley.edu/ | [prio] recent est credit: 0.00G in 45.42 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:22:16 | climateprediction.net | [prio] recent est credit: 0.00G in 45.42 sec, 0.000032 + -0.000000 ->0.000032
> 09.05.2023 20:22:16 | Einstein@Home | [prio] recent est credit: 133.85G in 45.42 sec, 9227.918513 + 8.941457 ->9236.859970
> 09.05.2023 20:22:16 | GPUGRID | [prio] recent est credit: 0.00G in 45.42 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:22:16 | Rosetta@home | [prio] recent est credit: 0.00G in 45.42 sec, 29.572077 + -0.001078 ->29.571000
> 09.05.2023 20:22:16 | World Community Grid | [prio] recent est credit: 3.58G in 45.42 sec, 264.783182 + 0.238328 ->265.021510
> 09.05.2023 20:22:16 | WUProp@Home | [prio] recent est credit: 0.00G in 45.42 sec, 0.001709 + -0.000000 ->0.001709
> 09.05.2023 20:22:16 | yoyo@home | [prio] recent est credit: 1.53G in 45.42 sec, 90.037764 + 0.102995 ->90.140759
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] schedule_cpus(): start
> 09.05.2023 20:22:16 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:16 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:16 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9592.022239
> 09.05.2023 20:22:16 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9236.859970 rs 9592.022239
> 09.05.2023 20:22:16 | Rosetta@home | [prio] -1000.003083 rsf 0.000000 rt 29.572077 rs 9592.022239
> 09.05.2023 20:22:16 | World Community Grid | [prio] -0.027629 rsf 1.000000 rt 265.021510 rs 9592.022239
> 09.05.2023 20:22:16 | yoyo@home | [prio] -1000.009397 rsf 0.000000 rt 90.140759 rs 9592.022239
> 09.05.2023 20:22:16 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:16 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:16 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:16 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9236.859970 rs 9592.022239
> 09.05.2023 20:22:16 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.002449 rs 9592.022239
> 09.05.2023 20:22:16 | World Community Grid | [prio] -0.027629 rsf 1.000000 rt 265.021510 rs 9592.022239
> 09.05.2023 20:22:16 | yoyo@home | [prio] -1000.009397 rsf 0.000000 rt 90.140759 rs 9592.022239
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] reserving 1.000000 of coproc ATI
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (AMD/ATI GPU, FIFO) (prio -1000.962973)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] add to run list: que_N_27_D_7_429141200_429141399_1683184524_433_1 (CPU, EDF) (prio -1000.009397)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] add to run list: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (CPU, EDF) (prio -1000.009551)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] add to run list: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (CPU, EDF) (prio -1000.009705)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2976_0 (CPU, FIFO) (prio -0.027629)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2959_0 (CPU, FIFO) (prio -0.027783)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198501_2359_1 (CPU, FIFO) (prio -0.027937)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2962_0 (CPU, FIFO) (prio -0.028091)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198501_2392_1 (CPU, FIFO) (prio -0.028244)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2972_0 (CPU, FIFO) (prio -0.028398)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2978_1 (CPU, FIFO) (prio -0.028552)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (CPU, FIFO) (prio -1001.002933)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (CPU, FIFO) (prio -1001.003087)
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] enforce_run_list(): start
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] preliminary job list:
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] 0: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] 1: que_N_27_D_7_429141200_429141399_1683184524_433_1 (MD: yes; UTS: no)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] 2: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (MD: yes; UTS: no)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] 3: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (MD: yes; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 4: MCM1_0198504_2976_0 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 5: MCM1_0198504_2959_0 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 6: MCM1_0198501_2359_1 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 7: MCM1_0198504_2962_0 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 8: MCM1_0198501_2392_1 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 9: MCM1_0198504_2972_0 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 10: MCM1_0198504_2978_1 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] 11: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (MD: no; UTS: no)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] 12: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (MD: no; UTS: no)
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] final job list:
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] 0: que_N_27_D_7_429141200_429141399_1683184524_433_1 (MD: yes; UTS: yes)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] 1: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (MD: yes; UTS: yes)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] 2: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (MD: yes; UTS: yes)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] 3: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 4: MCM1_0198504_2976_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 5: MCM1_0198504_2959_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 6: MCM1_0198501_2359_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 7: MCM1_0198504_2962_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 8: MCM1_0198501_2392_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 9: MCM1_0198504_2972_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] 10: MCM1_0198504_2978_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] 11: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] 12: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] scheduling que_N_27_D_7_429141200_429141399_1683184524_433_1 (high priority)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] scheduling ecm_ru_1683140721_10_469M.c282_2518_P1_0 (high priority)
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched_debug] scheduling ecm_ru_1683590148_10_1104.c217_7391_P1_0 (high priority)
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] scheduling h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2976_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2959_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198501_2359_1
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2962_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198501_2392_1
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2972_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2978_1
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] scheduling h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched_debug] scheduling h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched] Resuming h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched] Resuming task h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 using einstein_O3MD1 version 103 (GW-SSE2) in slot 10
> 09.05.2023 20:22:16 | Einstein@Home | [css] running h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 ( )
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched] Resuming ecm_ru_1683140721_10_469M.c282_2518_P1_0
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched] Resuming task ecm_ru_1683140721_10_469M.c282_2518_P1_0 using ecm version 70502 in slot 0
> 09.05.2023 20:22:16 | yoyo@home | [css] running ecm_ru_1683140721_10_469M.c282_2518_P1_0 ( )
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched] Resuming que_N_27_D_7_429141200_429141399_1683184524_433_1
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched] Resuming task que_N_27_D_7_429141200_429141399_1683184524_433_1 using m-queens version 1 in slot 1
> 09.05.2023 20:22:16 | yoyo@home | [css] running que_N_27_D_7_429141200_429141399_1683184524_433_1 ( )
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched] Resuming h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1
> 09.05.2023 20:22:16 | Einstein@Home | [cpu_sched] Resuming task h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 using einstein_O3MD1 version 103 (GW-SSE2) in slot 2
> 09.05.2023 20:22:16 | Einstein@Home | [css] running h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 ( )
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched] Resuming ecm_ru_1683590148_10_1104.c217_7391_P1_0
> 09.05.2023 20:22:16 | yoyo@home | [cpu_sched] Resuming task ecm_ru_1683590148_10_1104.c217_7391_P1_0 using ecm version 70502 in slot 11
> 09.05.2023 20:22:16 | yoyo@home | [css] running ecm_ru_1683590148_10_1104.c217_7391_P1_0 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198504_2976_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198504_2976_0 using mcm1 version 761 in slot 8
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198504_2976_0 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198504_2959_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198504_2959_0 using mcm1 version 761 in slot 12
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198504_2959_0 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198501_2359_1
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198501_2359_1 using mcm1 version 761 in slot 13
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198501_2359_1 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198504_2962_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198504_2962_0 using mcm1 version 761 in slot 4
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198504_2962_0 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198501_2392_1
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198501_2392_1 using mcm1 version 761 in slot 14
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198501_2392_1 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198504_2972_0
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198504_2972_0 using mcm1 version 761 in slot 15
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198504_2972_0 ( )
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming MCM1_0198504_2978_1
> 09.05.2023 20:22:16 | World Community Grid | [cpu_sched] Resuming task MCM1_0198504_2978_1 using mcm1 version 761 in slot 16
> 09.05.2023 20:22:16 | World Community Grid | [css] running MCM1_0198504_2978_1 ( )
> 09.05.2023 20:22:16 | Einstein@Home | [css] running h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (0.9 CPUs + 1 AMD/ATI GPU)
> 09.05.2023 20:22:16 | WUProp@Home | [css] running data_collect_v4_1683401806_231083_0 ( )
> 09.05.2023 20:22:16 |  | [cpu_sched_debug] enforce_run_list: end
> 09.05.2023 20:22:18 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:18 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:18 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9592.022239
> 09.05.2023 20:22:18 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9236.859970 rs 9592.022239
> 09.05.2023 20:22:18 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.002449 rs 9592.022239
> 09.05.2023 20:22:18 | World Community Grid | [prio] -0.027629 rsf 1.000000 rt 265.021510 rs 9592.022239
> 09.05.2023 20:22:18 | yoyo@home | [prio] -1000.009397 rsf 0.000000 rt 90.140759 rs 9592.022239
> 09.05.2023 20:22:18 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9621.593271
> 09.05.2023 20:22:18 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9621.593271
> 09.05.2023 20:22:18 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9621.593271
> 09.05.2023 20:22:18 | Einstein@Home | [prio] -1000.960014 rsf 0.000000 rt 9236.859970 rs 9621.593271
> 09.05.2023 20:22:18 | Rosetta@home | [prio] -1000.003073 rsf 0.000000 rt 29.571000 rs 9621.593271
> 09.05.2023 20:22:18 | World Community Grid | [prio] -0.027544 rsf 1.000000 rt 265.021510 rs 9621.593271
> 09.05.2023 20:22:18 | yoyo@home | [prio] -1000.009369 rsf 0.000000 rt 90.140759 rs 9621.593271
> 09.05.2023 20:22:33 | World Community Grid | General prefs: from World Community Grid (last modified 03-Apr-2023 11:14:37)
> 09.05.2023 20:22:33 | World Community Grid | Computer location: home
> 09.05.2023 20:22:33 | World Community Grid | General prefs: no separate prefs for home; using your defaults
> 09.05.2023 20:22:33 |  | Reading preferences override file
> 09.05.2023 20:22:34 |  | Preferences:
> 09.05.2023 20:22:34 |  | -  When computer is in use
> 09.05.2023 20:22:34 |  | -     'In use' means mouse/keyboard input in last 3.0 minutes
> 09.05.2023 20:22:34 |  | -     don't use GPU
> 09.05.2023 20:22:34 |  | -     max CPUs used: 12
> 09.05.2023 20:22:34 |  | -     Use at most 0% of the CPU time
> 09.05.2023 20:22:34 |  | -     suspend if non-BOINC CPU load exceeds 50%
> 09.05.2023 20:22:34 |  | -     max memory usage: 15.96 GB
> 09.05.2023 20:22:34 |  | -  When computer is not in use
> 09.05.2023 20:22:34 |  | -     max CPUs used: 12
> 09.05.2023 20:22:34 |  | -     Use at most 0% of the CPU time
> 09.05.2023 20:22:34 |  | -     suspend if non-BOINC CPU load exceeds 50%
> 09.05.2023 20:22:34 |  | -     max memory usage: 23.93 GB
> 09.05.2023 20:22:34 |  | -  Suspend if running on batteries
> 09.05.2023 20:22:34 |  | -  Leave apps in memory if not running
> 09.05.2023 20:22:34 |  | -  Store at least 0.20 days of work
> 09.05.2023 20:22:34 |  | -  Store up to an additional 0.30 days of work
> 09.05.2023 20:22:34 |  | -  max disk usage: 10.00 GB
> 09.05.2023 20:22:34 |  | -  (to change preferences, visit a project web site or select Preferences in the Manager)
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] Request CPU reschedule: Prefs update
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] Request CPU reschedule: Preferences override
> 09.05.2023 20:22:34 | https://boinc.thesonntags.com/collatz/ | [prio] recent est credit: 0.00G in 18.25 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:22:34 | http://setiathome.berkeley.edu/ | [prio] recent est credit: 0.00G in 18.25 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:22:34 | climateprediction.net | [prio] recent est credit: 0.00G in 18.25 sec, 0.000032 + -0.000000 ->0.000032
> 09.05.2023 20:22:34 | Einstein@Home | [prio] recent est credit: 0.01G in 18.25 sec, 9236.859970 + -0.134869 ->9236.725102
> 09.05.2023 20:22:34 | GPUGRID | [prio] recent est credit: 0.00G in 18.25 sec, 0.000000 + 0.000000 ->0.000000
> 09.05.2023 20:22:34 | Rosetta@home | [prio] recent est credit: 0.00G in 18.25 sec, 29.571000 + -0.000433 ->29.570567
> 09.05.2023 20:22:34 | World Community Grid | [prio] recent est credit: 0.00G in 18.25 sec, 265.021510 + -0.003870 ->265.017639
> 09.05.2023 20:22:34 | WUProp@Home | [prio] recent est credit: 0.00G in 18.25 sec, 0.001709 + -0.000000 ->0.001709
> 09.05.2023 20:22:34 | yoyo@home | [prio] recent est credit: 0.00G in 18.25 sec, 90.140759 + -0.001316 ->90.139444
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] schedule_cpus(): start
> 09.05.2023 20:22:34 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:34 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:34 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9591.882185
> 09.05.2023 20:22:34 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9236.725102 rs 9591.882185
> 09.05.2023 20:22:34 | Rosetta@home | [prio] -1000.003083 rsf 0.000000 rt 29.571000 rs 9591.882185
> 09.05.2023 20:22:34 | World Community Grid | [prio] -0.027629 rsf 1.000000 rt 265.017639 rs 9591.882185
> 09.05.2023 20:22:34 | yoyo@home | [prio] -1000.009397 rsf 0.000000 rt 90.139444 rs 9591.882185
> 09.05.2023 20:22:34 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:34 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:34 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:34 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9236.725102 rs 9591.882185
> 09.05.2023 20:22:34 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.002452 rs 9591.882185
> 09.05.2023 20:22:34 | World Community Grid | [prio] -0.027629 rsf 1.000000 rt 265.017639 rs 9591.882185
> 09.05.2023 20:22:34 | yoyo@home | [prio] -1000.009397 rsf 0.000000 rt 90.139444 rs 9591.882185
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] reserving 1.000000 of coproc ATI
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (AMD/ATI GPU, FIFO) (prio -1000.962973)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] add to run list: que_N_27_D_7_429141200_429141399_1683184524_433_1 (CPU, EDF) (prio -1000.009397)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] add to run list: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (CPU, EDF) (prio -1000.009551)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] add to run list: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (CPU, EDF) (prio -1000.009705)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2976_0 (CPU, FIFO) (prio -0.027629)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2959_0 (CPU, FIFO) (prio -0.027783)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198501_2359_1 (CPU, FIFO) (prio -0.027937)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2962_0 (CPU, FIFO) (prio -0.028091)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198501_2392_1 (CPU, FIFO) (prio -0.028244)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2972_0 (CPU, FIFO) (prio -0.028398)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] add to run list: MCM1_0198504_2978_1 (CPU, FIFO) (prio -0.028552)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (CPU, FIFO) (prio -1001.002933)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] add to run list: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (CPU, FIFO) (prio -1001.003087)
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] enforce_run_list(): start
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] preliminary job list:
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] 0: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] 1: que_N_27_D_7_429141200_429141399_1683184524_433_1 (MD: yes; UTS: yes)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] 2: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (MD: yes; UTS: yes)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] 3: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (MD: yes; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 4: MCM1_0198504_2976_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 5: MCM1_0198504_2959_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 6: MCM1_0198501_2359_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 7: MCM1_0198504_2962_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 8: MCM1_0198501_2392_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 9: MCM1_0198504_2972_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 10: MCM1_0198504_2978_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] 11: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] 12: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] final job list:
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] 0: que_N_27_D_7_429141200_429141399_1683184524_433_1 (MD: yes; UTS: yes)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] 1: ecm_ru_1683140721_10_469M.c282_2518_P1_0 (MD: yes; UTS: yes)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] 2: ecm_ru_1683590148_10_1104.c217_7391_P1_0 (MD: yes; UTS: yes)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] 3: h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 4: MCM1_0198504_2976_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 5: MCM1_0198504_2959_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 6: MCM1_0198501_2359_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 7: MCM1_0198504_2962_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 8: MCM1_0198501_2392_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 9: MCM1_0198504_2972_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] 10: MCM1_0198504_2978_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] 11: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] 12: h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 (MD: no; UTS: yes)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] scheduling que_N_27_D_7_429141200_429141399_1683184524_433_1 (high priority)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] scheduling ecm_ru_1683140721_10_469M.c282_2518_P1_0 (high priority)
> 09.05.2023 20:22:34 | yoyo@home | [cpu_sched_debug] scheduling ecm_ru_1683590148_10_1104.c217_7391_P1_0 (high priority)
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] scheduling h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2976_0
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2959_0
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198501_2359_1
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2962_0
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198501_2392_1
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2972_0
> 09.05.2023 20:22:34 | World Community Grid | [cpu_sched_debug] scheduling MCM1_0198504_2978_1
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] scheduling h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0
> 09.05.2023 20:22:34 | Einstein@Home | [cpu_sched_debug] scheduling h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1
> 09.05.2023 20:22:34 | Einstein@Home | [css] running h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_679_0 ( )
> 09.05.2023 20:22:34 | yoyo@home | [css] running ecm_ru_1683140721_10_469M.c282_2518_P1_0 ( )
> 09.05.2023 20:22:34 | yoyo@home | [css] running que_N_27_D_7_429141200_429141399_1683184524_433_1 ( )
> 09.05.2023 20:22:34 | Einstein@Home | [css] running h1_1491.20_O3aC01Cl0In0__O3MD1V2a_VelaJr1_1492.00Hz_414_1 ( )
> 09.05.2023 20:22:34 | yoyo@home | [css] running ecm_ru_1683590148_10_1104.c217_7391_P1_0 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198504_2976_0 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198504_2959_0 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198501_2359_1 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198504_2962_0 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198501_2392_1 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198504_2972_0 ( )
> 09.05.2023 20:22:34 | World Community Grid | [css] running MCM1_0198504_2978_1 ( )
> 09.05.2023 20:22:34 | Einstein@Home | [css] running h1_1118.60_O3aC01Cl1In0__O3MDFC2_CasA_1119.50Hz_364_0 (0.9 CPUs + 1 AMD/ATI GPU)
> 09.05.2023 20:22:34 | WUProp@Home | [css] running data_collect_v4_1683401806_231083_0 ( )
> 09.05.2023 20:22:34 |  | [cpu_sched_debug] enforce_run_list: end
> 09.05.2023 20:22:38 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:38 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:38 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000000 rs 9591.882185
> 09.05.2023 20:22:38 | Einstein@Home | [prio] -1000.962973 rsf 0.000000 rt 9236.725102 rs 9591.882185
> 09.05.2023 20:22:38 | Rosetta@home | [prio] -1000.000000 rsf 0.000000 rt 0.002452 rs 9591.882185
> 09.05.2023 20:22:38 | World Community Grid | [prio] -0.027629 rsf 1.000000 rt 265.017639 rs 9591.882185
> 09.05.2023 20:22:38 | yoyo@home | [prio] -1000.009397 rsf 0.000000 rt 90.139444 rs 9591.882185
> 09.05.2023 20:22:38 | https://boinc.thesonntags.com/collatz/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9621.452783
> 09.05.2023 20:22:38 | http://setiathome.berkeley.edu/ | [prio] -0.000000 rsf 1.000000 rt 0.000000 rs 9621.452783
> 09.05.2023 20:22:38 | climateprediction.net | [prio] -1000.000000 rsf 0.000000 rt 0.000032 rs 9621.452783
> 09.05.2023 20:22:38 | Einstein@Home | [prio] -1000.960014 rsf 0.000000 rt 9236.725102 rs 9621.452783
> 09.05.2023 20:22:38 | Rosetta@home | [prio] -1000.003073 rsf 0.000000 rt 29.570567 rs 9621.452783
> 09.05.2023 20:22:38 | World Community Grid | [prio] -0.027544 rsf 1.000000 rt 265.017639 rs 9621.452783
> 09.05.2023 20:22:38 | yoyo@home | [prio] -1000.009369 rsf 0.000000 rt 90.139444 rs 9621.452783

### PR DESCRIPTION
**Pull request by davidpanderson**
Old: if target CPU usage is (say) 1%,
we'd unthrottle, sleep 1 sec, throttle, and sleep 99 sec. A change to the usage pref wouldn't be enforced during that sleep.

New: do something every second; changes are seen immediately.

This makes a difference only when setting is very close to 0 or 100

Fixes #5231

### CODE REVIEW

**Comment by AenBleidd** [comment]
The code looks fine to me.
@RichardHaselgrove, any chance you can test this?

**Comment by RichardHaselgrove** [comment]
I'd say 'inconclusive'. Testing on Windows 7, I couldn't reproduce the stated problem with client 7.22.1: there didn't seem to be a delay when switching back from 1% to 100% of time. Having said that, it isn't obvious when CPU usage is paused - the task status in the Manager display (Advanced - tasks) remains as 'Running' throughout, and the only event logged is the 'Resume' (twice per task) when cpu_sched logging is enabled. The only clue is that elapsed time stops incrementing.

> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming wu_sf7_DS-16x11_Grp7856971of8000000_0
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming task wu_sf7_DS-16x11_Grp7856971of8000000_0 using GetDecics version 400 (default) in slot 3
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming wu_sf7_DS-16x11_Grp7859884of8000000_0
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming task wu_sf7_DS-16x11_Grp7859884of8000000_0 using GetDecics version 400 (default) in slot 1
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming wu_sf7_DS-16x11_Grp7283016of8000000_1
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming task wu_sf7_DS-16x11_Grp7283016of8000000_1 using GetDecics version 400 (default) in slot 2
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming wu_sf7_DS-16x11_Grp7868029of8000000_0
> 11/05/2023 12:21:14 | NumberFields@home | [cpu_sched] Resuming task wu_sf7_DS-16x11_Grp7868029of8000000_0 using GetDecics version 400 (default) in slot 0

I switched to the artifact for this PR, with some difficulty: Windows Security Essentials flagged the client archive as a virus (Manager and apps were clean). I had to download it on a Linux machine and email it to myself ... I couldn't detect any change in behaviour between old and new.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, thank you for testing this.

>  I couldn't detect any change in behaviour between old and new.

I have asked the reported of this issue to test this on their side. 

> Windows Security Essentials flagged the client archive as a virus

Definitely a false positive detection. If you have any doubts - you can use this service to check any file with several endpoint security software: https://www.virustotal.com/gui/home/upload

File: client/app.cpp [hunk 1]
```diff
@@ -1265,25 +1265,35 @@ void* throttler(void*) {
     diagnostics_thread_init();
     while (1) {
         double limit = gstate.current_cpu_usage_limit();
+
+        // if limit is 100, make sure we're not throttled
+        //
         if (limit >= 100) {
+            if (gstate.tasks_throttled) {
+                gstate.active_tasks.unsuspend_all(SUSPEND_REASON_CPU_THROTTLE);
```
Comment (BrianNixon) [inline client/app.cpp:1273]: Does this need the mutex locking?

**Comment by davidpanderson** [comment]
I think I fixed the problem Brian pointed out, and one or two others.  Please test again.

**Review by AenBleidd — APPROVED** [review]
