### PR TITLE
[Android] Fix counter is up on retry transfer

### LINKED ISSUE #3928: [Android] Counter is up on retry transfer.
> **Describe the bug**
> A clear and concise description of what the bug is.
Counter is up on retry transfer.

> **Steps To Reproduce**
1.  Add a new project
2. When project start to transfer, cut the internet.
3. See the retry msg and the counter is up.

> **Expected behavior**
> A clear and concise description of what you expected to happen.
Counter should be down, when it zero, it should retry to download by itself.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.
Screenshot_20200714-091151

> **System Information**
 - OS: Android from 4.1-10.
 - BOINC Version:  7.4.53 7.16.3 and master (old bug).

> **Additional context**
> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by talregev**
Fixes #3928
implement cpp code:
https://github.com/BOINC/boinc/blob/b2b790e6d740a811d25bf58ecc3dc7fe067602a6/clientgui/ViewTransfers.cpp#L851-L868

### CODE REVIEW

**Comment by talregev** [comment]
Example when internet is cut off: 

image

File: android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt [hunk 1]
```diff
@@ -24,6 +24,11 @@ import androidx.core.os.ParcelCompat.readBoolean
 import androidx.core.os.ParcelCompat.writeBoolean
 import java.io.Serializable
 
+enum class TransferStatus(val status: Int) {
+    ERR_GIVEUP_DOWNLOAD(-114),
+    ERR_GIVEUP_UPLOAD(-115),
```
Comment (AenBleidd) [inline android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt:29]: extra coma is not needed

**Review by AenBleidd — CHANGES_REQUESTED** [review]

File: android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt (hunk 1 above)
Comment (talregev) [reply android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Transfer.kt]: done

**Review by AenBleidd — APPROVED** [review]
