### PR TITLE
macOS: fix chflags failure on fresh installs breaking permission setup

### LINKED ISSUE #6963: macOS: Fresh install leaves all files root:wheel — Fix_BOINC_Users and BOINC_Finish_Install both fail to repair
## Description

After a fresh BOINC install on macOS, all files and directories under `/Library/Application Support/BOINC Data/`, the app bundle, and the screensaver are owned by `root:wheel` instead of the expected `boinc_master`/`boinc_project` ownership. This causes BOINC Manager to fail at launch with:

> **BOINC ownership or permissions are not set properly; please reinstall BOINC.**

The built-in repair tools (`Fix_BOINC_Users` and `BOINC_Finish_Install.app`) both fail to resolve the issue.

**Suggested labels:** `C: Installer`, `C: Client - Setup`, `OS: MacOs`, `P: Major`, `PR: Bugfix`

## Environment

- **BOINC version:** 8.2.9
- **macOS:** 26.4 (Tahoe), build 25E246
- **Architecture:** Apple Silicon (arm64)
- **Install method:** Standard .pkg installer

## Steps to Reproduce

1. Install BOINC 8.2.9 via the official .pkg installer
2. Launch BOINC Manager
3. Observe error: "BOINC ownership or permissions are not set properly" (Error code -1005)

## What I Observed

After installation, everything is owned by `root:wheel`:

```
$ ls -la /Library/Application\ Support/BOINC\ Data/
drwxr-xr-x  16 root  wheel  512 Apr  7 16:32 .
-rwxr-xr-x   1 root  wheel  ...  Fix_BOINC_Users
-rwxr-xr-x   1 root  wheel  ...  Run_Podman
drwxr-xr-x   4 root  wheel  ...  switcher
drwxr-xr-x   3 root  wheel  ...  projects
...

$ ls -la /Library/Screen\ Savers/BOINCSaver.saver/Contents/Resources/
-rwxrwxr-x  1 root  wheel  ...  gfx_switcher

$ ls -la /Applications/BOINCManager.app/Contents/Resources/
-rwxr-xr-x  1 root  wheel  ...  boinc    # missing setuid/setgid bits
```

The `boinc_master` and `boinc_project` users and groups **do exist** — they were created correctly by the installer. Only the file ownership/permissions were not applied.

### Fix_BOINC_Users
```
$ sudo /Library/Application\ Support/BOINC\ Data/Fix_BOINC_Users
```
Runs and exits silently with no output and no effect — all files remain `root:wheel`.

### BOINC_Finish_Install.app
```
$ sudo /Library/Application\ Support/BOINC\ Data/BOINC_Finish_Install.app/Contents/MacOS/BOINC_Finish_Install
```
Appears to hang indefinitely. Had to kill with Ctrl+C.

## Error Codes Encountered

After manually fixing permissions one-by-one (guided by reading `check_security.cpp`), I hit these sequentially:

| Error Code | Cause |
|------------|-------|
| **-1005** | `boinc` client binary missing `S_ISUID \| S_ISGID` bits |
| **-1102** | `gfx_switcher` in screensaver has wrong group (wheel instead of boinc_master) |
| **-1201** | Project subdirectory has wrong group (boinc_master instead of boinc_project) |
| **-1203** | Project subdirectory has wrong permission bits |
| **-1072** | `BOINC podman` directory has wrong group (wheel instead of boinc_project) |

## Workaround

I wrote a shell script that fixes all ownership and permissions based on what `check_security.cpp` expects. This resolved the issue completely:

```bash
#!/bin/bash
# Fix ALL BOINC ownership and permissions based on check_security.cpp
set -e

DATA="/Library/Application Support/BOINC Data"
APP="/Applications/BOINCManager.app"
SAVER="/Library/Screen Savers/BOINCSaver.saver"
PODMAN="/Library/Application Support/BOINC podman"

# BOINC Data directory
chown boinc_master:boinc_master "$DATA"
chmod 0775 "$DATA"

# Switcher directory and binaries
chown boinc_master:boinc_master "$DATA/switcher"
chmod 0550 "$DATA/switcher"
chown root:boinc_master "$DATA/switcher/switcher"
chmod 4050 "$DATA/switcher/switcher"
chown root:boinc_master "$DATA/switcher/setprojectgrp"
chmod 4050 "$DATA/switcher/setprojectgrp"

# Utility binaries
chown root:boinc_master "$DATA/Fix_BOINC_Users"
chmod 4555 "$DATA/Fix_BOINC_Users"
chown root:boinc_master "$DATA/Run_Podman"
chmod 4555 "$DATA/Run_Podman"

# Config files
chown boinc_master:boinc_master "$DATA/ss_config.xml"
chmod 0664 "$DATA/ss_config.xml"
[ -f "$DATA/gui_rpc_auth.cfg" ] && chown boinc_master:boinc_master "$DATA/gui_rpc_auth.cfg" && chmod 0660 "$DATA/gui_rpc_auth.cfg"

# Projects directory
chown boinc_master:boinc_project "$DATA/projects"
chmod 0770 "$DATA/projects"
find "$DATA/projects" -mindepth 1 -maxdepth 1 -type d -exec chown boinc_master:boinc_project {} \;
find "$DATA/projects" -mindepth 1 -maxdepth 1 -type d -exec chmod 0775 {} \;
find "$DATA/projects" -mindepth 2 -exec chgrp boinc_project {} \;

# Slots directory
if [ -d "$DATA/slots" ]; then
    chown boinc_master:boinc_project "$DATA/slots"
    chmod 0770 "$DATA/slots"
    find "$DATA/slots" -mindepth 1 -maxdepth 1 -type d -exec chown boinc_master:boinc_project {} \;
    find "$DATA/slots" -mindepth 1 -maxdepth 1 -type d -exec chmod 0775 {} \;
fi

# Locale and remaining data files
chown -R boinc_master:boinc_master "$DATA/locale"
for f in "$DATA/all_projects_list.xml" "$DATA/boinc_logo_black.jpg" "$DATA/LiberationSans-Regular.ttf" "$DATA/boincscr" "$DATA/detect_rosetta_cpu" "$DATA/login_token.txt"; do
    [ -e "$f" ] && chown boinc_master:boinc_master "$f"
done

# App bundle + boinc client setuid/setgid
chown -R boinc_master:boinc_master "$APP"
chmod 6555 "$APP/Contents/Resources/boinc"

# Podman directory
if [ -d "$PODMAN" ]; then
    chown boinc_master:boinc_project "$PODMAN"
    chmod 0770 "$PODMAN"
    [ "$(find "$PODMAN" -mindepth 1 -maxdepth 1 2>/dev/null)" ] && find "$PODMAN" -mindepth 1 -exec chown boinc_project:boinc_project {} \;
fi

# Screensaver
if [ -d "$SAVER" ]; then
    chown -R root:boinc_master "$SAVER"
    [ -f "$SAVER/Contents/Resources/gfx_switcher" ] && chmod 4050 "$SAVER/Contents/Resources/gfx_switcher"
fi

echo "All BOINC permissions fixed."
```

Run with `sudo bash fix_boinc_permissions.sh`.

## Related Issues

This appears to be the same root cause as #5551 (closed), which reported the same -1005 error after command-line install on macOS Sonoma.

## Suggestions

1. The `.pkg` installer's postinstall script should reliably set all ownership and permissions — something appears to be failing silently on recent macOS versions.
2. `Fix_BOINC_Users` should produce output (success/failure) rather than exiting silently when it can't fix anything.
3. `BOINC_Finish_Install.app` should not hang when run from the terminal.
4. Consider having BOINC Manager itself offer to run the repair (via authorization prompt) when it detects permission errors, rather than just telling the user to reinstall.

Thank you for all the work on BOINC — happy to provide any additional info or logs that would help! 🙏

### PR DESCRIPTION
**Pull request by RedesignedRobot**
Fixes #6963

## Problem

`CreateUserAndGroup()` runs `chflags hidden` on `/Users/<name>`, but on fresh installs the home directory is `/var/empty`. `chflags` fails with "No such file or directory", `CreateBOINCUsersAndGroups()` returns 256 on all 5 retries, and the permission-setting functions never execute.

Also: `buf2` was overwritten from the filesystem path (`/Users/`) to the DSCL path (`/users/`) at line 967, so the wrong path was being passed.

## Changes

**`clientgui/mac/SetupSecurity.cpp`:**
- Check `access(path, F_OK)` before calling `chflags`
- Rebuild `buf2` to correct filesystem path

**`mac_installer/PostInstall.cpp`:**
- Fix off-by-one in `REPORT_ERROR(i >= RETRY_LIMIT)` (never true inside the loop)
- Return non-zero when security setup fails after all retries
- Add missing newlines to printf calls

### CODE REVIEW

**Comment by AenBleidd** [comment]
@CharlieFenton, please take a look at this PR.
Please keep in mind it was generated by AI and thus cannot be trusted.

File: clientgui/mac/SetupSecurity.cpp [hunk 1]
```diff
@@ -986,25 +987,37 @@ static OSStatus CreateUserAndGroup(char * user_name, char * group_name) {
...
-        }   // end if (WIFEXITED(status)) else
-    }       // end if waitpid returned 0 sstaus else
-if (err)
-    return err;
+    // Note: buf2 was overwritten to the DSCL path "/users/<name>" above, so
+    // reconstruct the filesystem path. Only run chflags if the directory
+    // actually exists — on fresh installs, system users (boinc_master,
+    // boinc_project) have NFSHomeDirectory=/var/empty and no directory
+    // under /Users/, so chflags would fail with "No such file or directory".
+    {
```
Comment (AenBleidd) [inline clientgui/mac/SetupSecurity.cpp]: Why this extra scope is here?

File: clientgui/mac/SetupSecurity.cpp [hunk 2]
```diff
@@ -1100,18 +1113,35 @@ static OSStatus DoSudoPosixSpawn(const char *pathToTool, char *arg1, char *arg2,
     int                 result = 0;
     int                 status = 0;
     extern char         **environ;
+    Boolean             alreadyRoot = (geteuid() == 0);
```
Comment (AenBleidd) [inline clientgui/mac/SetupSecurity.cpp]: If this is not an issue as we already found out, then why this is still here?

File: clientgui/mac/SetupSecurity.cpp [hunk 3]
```diff
@@ -1100,18 +1113,35 @@ static OSStatus DoSudoPosixSpawn(const char *pathToTool, char *arg1, char *arg2,
...
-        args[0] = "/usr/bin/sudo";
-        args[1] = toolName;
-        args[2] = arg1;
-        args[3] = arg2;
-        args[4] = arg3;
-        args[5] = arg4;
-        args[6] = arg5;
-        args[7] = arg6;
-        args[8] = NULL;
+        if (alreadyRoot) {
```
Comment (AenBleidd) [inline clientgui/mac/SetupSecurity.cpp]: Same for this

File: clientgui/mac/SetupSecurity.cpp [hunk 4]
```diff
@@ -1124,7 +1154,9 @@ static OSStatus DoSudoPosixSpawn(const char *pathToTool, char *arg1, char *arg2,
 
         errno = 0;
 
-        result = posix_spawnp(&thePid, "/usr/bin/sudo", NULL, NULL, args, environ);
+        result = alreadyRoot
```
Comment (AenBleidd) [inline clientgui/mac/SetupSecurity.cpp]: And this

File: clientgui/mac/SetupSecurity.cpp [hunk 5]
```diff
@@ -1181,6 +1213,25 @@ void ShowSecurityError(const char *format, ...) {
     va_start(args, format);
     vfprintf(stderr, format, args);
     va_end(args);
+
```
Comment (AenBleidd) [inline clientgui/mac/SetupSecurity.cpp]: This is not needed as the installer is already writing logs to the file

**Review by AenBleidd — CHANGES_REQUESTED** [review]

**Review by CharlieFenton — APPROVED** [review]

**Comment by CharlieFenton** [comment]
@AenBleidd: I can't merge because it is blocked due to your requested changes, which I think have all been made. Please clear the block and merge.

**Comment by CharlieFenton** [comment]
@RedesignedRobot Thank you for tracking down the cause of this bug and submitting this fix, as well as your responsiveness to @AenBleidd's requests for changes. I really appreciate that. We hope you will continue to assist with making BOINC reliable, especially on the Mac.

And thank you to @AenBleidd for your review and handling the needed changes.

**Review by AenBleidd — APPROVED** [review]
