### PR TITLE
[Android] Fix Tasks loading

### LINKED ISSUE #2123: Android Boinc shows 0 tasks
If there are too much tasks (more than 100?) are running but the android client shows 0 tasks.

This happens on a Galaxy S5 Neo with Android 6.0.1.

See also https://boinc.berkeley.edu/dev/forum_thread.php?id=11640

### PR DESCRIPTION
**Pull request by AenBleidd**
On modern devices with more than 4 cores or when there is a big tasks cache set could happen a situation when 0 tasks are shown.
This happens because of the limit of 1MB to transfer data between processes.
This commit breaks this flow and instead adds a possibility to load data by chunks.
Also small optimization implemented to update only active tasks every second.
Full update is done every 10 seconds now because most of the time non-active tasks are not updated so often.

This fixes #2123

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Review by Isira-Seneviratne — APPROVED** [review]

**Comment by AenBleidd** [comment]
@BOINC/committer, please merge

File: android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt [hunk 1]
```diff
@@ -89,29 +91,78 @@ class TasksFragment : Fragment() {
         super.onPause()
     }
 
-    private fun loadData() {
-        // try to get current client status from monitor
-        val tmpA = try {
-            BOINCActivity.monitor!!.tasks
+    private fun loadTasks(start: Int, count: Int, isActive: Boolean): MutableList<Result>? {
+        return try {
+            BOINCActivity.monitor!!.getTasks(start, count, isActive)
```
Comment (Isira-Seneviratne) [inline android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt:96]:
```suggestion
        return BOINCActivity.monitor?.getTasks(start, count, isActive) ?: emptyList()
```

File: android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt [hunk 2]
```diff
@@ -89,29 +91,78 @@ class TasksFragment : Fragment() {
         super.onPause()
     }
 
-    private fun loadData() {
-        // try to get current client status from monitor
-        val tmpA = try {
-            BOINCActivity.monitor!!.tasks
+    private fun loadTasks(start: Int, count: Int, isActive: Boolean): MutableList<Result>? {
```
Comment (Isira-Seneviratne) [inline android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt:94]:
```suggestion
    private fun loadTasks(start: Int, count: Int, isActive: Boolean): MutableList<Result> {
```

File: android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt (hunk 1 above)
Comment (AenBleidd) [reply android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt]: Fixed

File: android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt (hunk 2 above)
Comment (AenBleidd) [reply android/BOINC/app/src/main/java/edu/berkeley/boinc/TasksFragment.kt]: Fixed
