### PR TITLE
client: fix bug where avg_ncpus for anonymous platform apps defaults to zero

### LINKED ISSUE #6012: app_info.xml configured projects break when 8.1.0-1586 client is restarted
### Describe the bug

When i restart boinc-client while running sidock using app_info all tasks display 0 cpus used and attempt to run all tasks at the same time disregarding use 50% of the cpus.

Image

### Steps to reproduce

1. set sidock to use app_info.xml using this guide: https://www.sidock.si/sidock/forum_thread.php?id=125&postid=2167
2. receive tasks.
3. run sudo systemctl restart boinc-client

### Expected behavior

Image

### Screenshots

_No response_

### System information

OS: Ubuntu 24.04
boinc-client 8.1.0-1586

### Additional context

It doesn't happen on 8.0.4-875

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #6012

### CODE REVIEW

File: client/cs_statefile.cpp [hunk 1]
```diff
@@ -856,7 +856,8 @@ int CLIENT_STATE::write_state_file_if_needed() {
 
 // look for app_versions.xml file in project dir.
 // If find, get app versions from there,
-// and use "anonymous platform" mechanism for this project
```
Comment (Vulpine05) [inline client/cs_statefile.cpp:859]: Apologies for being the grammar police, but shouldn't the line above say "If found" instead of "If find"?

**Review by AenBleidd — APPROVED** [review]

File: client/cs_statefile.cpp (hunk 1 above)
Comment (davidpanderson) [reply client/cs_statefile.cpp:859]: I think that 'If find' is comment-shorthand for 'If you find it'.
