### PR TITLE
Manager/Lib: fix 'New Manager window' function on Linux

### LINKED ISSUE #1177: launch another boinc mgr -> execv: Permission denied
**Reported by toralf on 16 Jul 42651934 12:46 UTC**
Under a stable Gentoo Linux I got that error message in .xsession-errors when I tried to to that action.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1205

### PR DESCRIPTION
**Pull request by ChristianBeer**
This was not working because the manager was not detecting its own executable name and path so it couldn't start a new instance of itself. Windows and Mac use different codepaths so it worked there.
The new library function can be extended for Windows and Mac to avoid code duplication.

Fixes #1177

### CODE REVIEW

**Comment by ChristianBeer** [comment]
Nice regression. I kind of saw it coming when I wrote the code but didn't test in the end. Good that we have Travis for that. I'm going to fix that later.

**Comment by ChristianBeer** [comment]
Fixed and ready to be merged.

**Comment by ChristianBeer** [comment]
We might want to hold of on merging this. There is a regression on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858187 which already has this fix as part of 7.6.33+dfsg-10

**Comment by ChristianBeer** [comment]
Might also fix #1555 (referenced so the status of this PR is visible in the issue)

File: lib/util.cpp [hunk 1]
```diff
@@ -625,3 +625,24 @@ double rand_normal() {
...
 }
+
+// determines the real path and filename of the current process
+// not the current working directory
+//
+int get_real_executable_path(char* path, size_t max_len) {
+#ifdef HAVE__PROC_SELF_EXE
+    int ret = readlink("/proc/self/exe", path, max_len);
+    if ( ret >= 0) {
+        path[ret] = '\0'; // readlink does not null terminate
```
Comment (JuhaSointusalo) [inline lib/util.cpp]: In the somewhat unlikely event that the link is `max_len` bytes long or longer this write goes one past the end of the buffer. Better have `max_len-1` with `readlink`.

**Comment by davidpanderson** [comment]
Thanks.
