### PR TITLE
fix non-BOINC CPU usage limit on Win and Linux

### LINKED ISSUE #4327: Non-BOINC CPU usage time is incorrect
BOINC's calculation of non-BOINC CPU usage time is incorrect, as processes which exited within the sample interval (typically 10 seconds) are not taken into consideration. This leads to BOINC underestimating the non-BOINC CPU usage, especially in situations where a lot of short-lived processes are present.

We run BOINC as SCHED_IDLE batch process on our Continuous-Integration (CI) nodes and configured BOINC to suspend once more than 10% CPU time is consumed by other applications. But since short-lived processes are very common when compiling (C/C++) projects, BOINC is constantly underestimating the non-BOINC CPU usage. As result, it often kicks in, while a CI jobs is actually fully utilizing the system. Needles to say, that this behavior is undesirable.

I saw that this shortcoming was already identified in https://github.com/BOINC/boinc/pull/3939. But this PR seems to be stalled. Hence, besides this issue acting as tracking issue for the deficiency, please feel encouraged to continue work on PR #3939 by it. :)

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #4327, #4328

The pref "suspend_cpu_usage" lets you suspend BOINC computing
when the non-BOINC CPU usage (NBCU) exceeds a threshold T.

NBCU excludes BOINC-related processes
- the BOINC client
- the BOINC Manager
- BOINC apps and their process trees
- graphics apps
- VBox daemon
    This can use significant time.
    We count it as BOINC-related only if BOINC is running a Vbox app

NBCU also excludes low-priority processors:
"niced" on Linux, idle class on Win.
We don't want such processes to keep BOINC from computing.

This preference is enforced every 10 seconds.
The client estimates the NBCU over the last 10 sec,
and suspends BOINC processing if the load exceeds T

Currently, NBCU is estimated by scanning the list of all processes,
skipping the types of processes listed above,
and adding up the user and kernel time of others.
This gives a value Tcur.
Let Tprev be the previous value (from 10 seconds ago).
Let X = (Tcur - Tprev)/(ncpus*10).
We suspend processing if X/(ncpus*10) > T

This approach is fundamentally flawed.
It would be fine if processes never exited.
But if a process exits during a given 10-sec period,
its time is included in Tprev but not Tcur,
in which case X is wrong; it may be negative.
This can cause false negatives (not suspending when we should have suspended).

To fix this, we need a different approach.
We shouldn't estimate total CPU by adding up current processes.
Fortunately, most OS's have an API for getting total CPU time.
On Linux this is broken down into a lot of categories,
including "niced" processes.
On Win it's only broken down by user/kernel.

The new approach is basically:
every 10 sec, get the increase Y in total CPU (as reported by the OS).
Then estimate the total CPU time B
used by BOINC-related and low-priority processes in the last 10 sec,
and let X = Y - B.
Suspend processing if X/(ncpus*10) > T

We'll estimate B by scanning the process list and adding up
the totals for BOINC-related processes,
and computing the delta since 10 sec ago.
This is subject to the same error as above:
when these processes exit, B will be underestimated (typically negative),
so X will be overestimated, causing a false positive.
However, this happens infrequently;
BOINC jobs low-priority processes are generally long-running.
And we can avoid false positives by setting X to zero if B is negative.

Because of the possible error in X,
we'll use a conservative approach to resuming from a suspension:
if we're currently suspended because of CPU usage,
unsuspend only if X < T for two consecutive 10-sec periods

### CODE REVIEW

**Comment by AenBleidd** [comment]
@Flowdalic, could you please test this and confirm that it works in your case?

**Review by AenBleidd — APPROVED** [review]
Code itself looks ok to me. Still need to be verified IMHO

**Comment by Vulpine05** [comment]
> Code itself looks ok to me. Still need to be verified IMHO

I am building it right now and was going to test it.  I cannot say I know exactly how to test, but I will at least see if I observe anything different.  I will see what I can do in the next week, but don't wait for me if you are ready to merge.

**Comment by AenBleidd** [comment]
@Vulpine05, we do not rush here. And mostly this need to be tested by @Flowdalic since they have a very special conditions

**Comment by davidpanderson** [comment]
I tested it (not exhaustively) on Win and Linux.  I'm working with Charlie to see if there's a "get total CPU" API on Mac OS as well.

File: lib/procinfo_unix.cpp [hunk 1]
```diff
@@ -263,3 +263,24 @@ int procinfo_setup(PROC_MAP& pm) {
...
+double total_cpu_time() {
+    char buf[1024];
+    static FILE *f=NULL;
+    static double scale;
+    if (!f) {
+        f = fopen("/proc/stat", "r");
+        long hz = sysconf(_SC_CLK_TCK);
+        scale = 1./hz;
+    } else {
+        fflush(f);
```
Comment (Flowdalic) [inline lib/procinfo_unix.cpp:279]: I believe `fflush()` is unnecessary if followed by `rewind()`  (which is basically `fseek()`).

File: lib/procinfo_unix.cpp [hunk 2]
```diff
@@ -263,3 +263,24 @@ int procinfo_setup(PROC_MAP& pm) {
...
+        rewind(f);
+    }
+    if (!fgets(buf, 256, f)) return 0;
```
Comment (Flowdalic) [inline lib/procinfo_unix.cpp:282]: Why not `return -1` to signal the error condition?

File: lib/procinfo_unix.cpp [hunk 3]
```diff
@@ -263,3 +263,24 @@ int procinfo_setup(PROC_MAP& pm) {
...
+    double user, nice;
+    sscanf(buf, "cpu %lf %lf", &user, &nice);
```
Comment (Flowdalic) [inline lib/procinfo_unix.cpp:284]: Missing error handling for `sscanf()` and `user` and `nice` could be declared as `long`.

File: lib/procinfo.h [hunk 4]
```diff
@@ -82,4 +82,10 @@ extern void procinfo_non_boinc(PROCINFO&, PROC_MAP&);
 extern double process_tree_cpu_time(int pid);
     // get the CPU time of the given process and its descendants
 
+extern double total_cpu_time();
+    // total CPU time, as reported by OS
```
Comment (Flowdalic) [inline lib/procinfo.h:86]: The comment in `procinfo_unix.cpp` more accurately states that this returns *user-mode* CPU time. Both comments are missing the returned unit, which is, I believe, seconds.

File: lib/procinfo.cpp [hunk 5]
```diff
@@ -135,10 +135,34 @@ void procinfo_non_boinc(PROCINFO& procinfo, PROC_MAP& pm) {
...
+    double sum = 0;
+    PROC_MAP::iterator i;
+    for (i=pm.begin(); i!=pm.end(); ++i) {
+        PROCINFO& p = i->second;
+#ifdef _WIN32
+        if (p.id == 0) continue;    // idle process
+#endif
+        if (
+            p.is_boinc_app
+            || p.is_low_priority
```
Comment (Flowdalic) [inline lib/procinfo.cpp:157]: The following is on indirectly related to this PR.

 `is_low_priority()` currently only does consider the "lowest-priority" nice value (unless I am mistaken). Once could argue that all "low-priority" nice values should be considered.

In any case, `is_low_priority()` should also return true for processes running under `SCHED_IDLE`.

**Comment by Flowdalic** [comment]
Glad to see that there is finally movement towards fixing this long standing issue. Thanks everyone! :)

> And mostly this need to be tested by @Flowdalic since they have a very special conditions

I tend to believe that we do *not* have "very special conditions". We have a bunch of machines for continuous integration and scientific computation. We donated CPU time by running BOINC on those as low-priority batch job, so that it wont affect the primary users. For that we just set it to run as SCHED_IDLE job. This worked perfectly, especially with [kernels >= 5.4 where SCHED_IDLE got significantly improved](https://lwn.net/Articles/805317/). We also set BOINC to stop if the non-BOINC usage was above a threshold. Just to make extra sure that nobody could complain about BOINC draining resources from their jobs.

I believe it is very common for people and/or organization that they are willing to donate CPU time by running BOINC as low-priority batch job on their machines. With the only requirement being that it does not affect normal operations.

What we saw was that BOINC would often not release the resources, because of the non-BOINC usage calculation being flawed. Then I patched BOINC with https://github.com/BOINC/boinc/pull/4336 and https://github.com/BOINC/boinc/pull/4328, which improved the user experience.

Ultimately, we had to to turn off BOINC, because building and distributing a custom BOINC .deb was not longer sustainable. I can not tell when we will re-enabled BOINC again, or if we do so ever. Hence I am unfortunately unable to test this PR.

However, I left some comments in-line. I guess my main point is not directly related to this PR, but `is_low_priority()` should also return `true` for processes that run with the `SCHED_IDLE` scheduling policy.

File: lib/procinfo_unix.cpp (hunk 1 above)
Comment (davidpanderson) [reply lib/procinfo_unix.cpp:279]: without fflush(), fgets() will return the same buffered data

File: lib/procinfo_unix.cpp (hunk 3 above)
Comment (davidpanderson) [reply lib/procinfo_unix.cpp:284]: I added several error checks.  nice is double to avoid 32-bit overflow

File: lib/procinfo.h (hunk 4 above)
Comment (davidpanderson) [reply lib/procinfo.h:86]: fixed.  Time in BOINC are always seconds unless otherwise specified

File: lib/procinfo_unix.cpp (hunk 2 above)
Comment (davidpanderson) [reply lib/procinfo_unix.cpp:282]: for now, we'll handle errors by writing an error message and returning 0 (so the limit will have no effect).

File: lib/procinfo.cpp (hunk 5 above)
Comment (davidpanderson) [reply lib/procinfo.cpp:157]: Maybe do this later.  It would require calling sched_getscheduler() for every process, every 10 sec.

**Comment by CharlieFenton** [comment]
It appears to me that your code is looking at total CPU time since the system was booted, rather than the recent CPU times, for both `boinc_related_cpu_time()` and `total_cpu_time()`. I think you need to calculate the equivalent of `(new_cpu_time - last_cpu_time)/diff`for both  in `ACTIVE_TASK_SET::get_memory_usage()`both `boinc_related_cpu_time()` and `total_cpu_time()`, as you do for the older method.

File: lib/procinfo_unix.cpp (hunk 1 above)
Comment (Flowdalic) [reply lib/procinfo_unix.cpp:283]: FWIW I am not totally convinced that this is the case, since fseek() will also flush the data (and rewind() is based on fseek()). At least if my memory serves me right.

**Comment by davidpanderson** [comment]
The code computes the difference between successive totals.
See app.cpp line 495

**Comment by CharlieFenton** [comment]
> The code computes the difference between successive totals.
See app.cpp line 495

@davidpanderson Thanks, I see that now.
