### PR TITLE
client and server: increase p_features size from 1024 to 8192.

### LINKED ISSUE #5122: Ryzen 7950x lacks feature sse2
**Describe the bug**
Einstein@Home tasks are being rejected with an error
**[version] CPU [' family 25 model 97 stepping 2 '] lacks feature ' sse2 '**

`
28.02.2023 17:45:16 |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi u
`
as you can see the list is truncated because the internal buffer isn't large enough, but I'm not sure it's the reason for the original error...

cat /proc/cpuinfo
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 97
model name      : AMD Ryzen 9 7950X 16-Core Processor
stepping        : 2
microcode       : 0xa601203
cpu MHz         : 4499.798
cache size      : 1024 KB
physical id     : 0
siblings        : 32
core id         : 0
cpu cores       : 16
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 8999.57
TLB size        : 3584 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```

I manually tested cpuid feature check and it also says sse2 IS supported.

**Steps To Reproduce**
add a project Einstein@Home and enable Multi-Directional Gravitational Wave search on O3 (CPU)

**Expected behavior**
it doesn't accept work due to a missing feature sse2 which is supported on this CPU (no VMs or hacks are involved). Other boinc projects work just fine.

**System Information**
 - `OS: Linux desktop-b49ep3v.easy.local 6.2.0-1275.native #1 SMP Wed Feb 22 18:59:06 PST 2023 x86_64 GNU/Linux`
 - BOINC Version: 7.20.5

**Additional context**
see related code
https://github.com/BOINC/boinc/blob/master/lib/hostinfo.h#L53
https://github.com/BOINC/boinc/blob/master/client/hostinfo_unix.cpp#L530
https://github.com/BOINC/boinc/blob/master/client/hostinfo_unix.cpp#L683

and the original report https://einsteinathome.org/cs/content/ryzen-7950x-lacks-feature-sse2

let me know if there's more info / logs or tests I can provide. Thanks!

### PR DESCRIPTION
**Pull request by davidpanderson**
1024 wasn't enough for some CPUs.
This caused some hosts to not get sse3 app versions, for example.

Note: ideally we'd change this to std::string.
But that would have disrupted the code that populates it (hostinfo_unix.cpp, hostinfo_win.cpp).
Easier/safer to do it this way.

Fixes #5122

### CODE REVIEW

**Comment by AenBleidd** [comment]
Android and Webassembly are expected to fail, so could be ignored for now

File: client/hostinfo_unix.cpp [hunk 1]
```diff
@@ -485,7 +485,7 @@ static void parse_meminfo_linux(HOST_INFO& host) {
 // See http://people.nl.linux.org/~hch/cpuinfo/ for some examples.
 //
 static void parse_cpuinfo_linux(HOST_INFO& host) {
-    char buf[1024], features[P_FEATURES_SIZE], model_buf[1024];
+    char buf[P_FEATURES_SIZE], features[P_FEATURES_SIZE], model_buf[1024];
```
Comment (AenBleidd) [inline client/hostinfo_unix.cpp:488]: You increased the size of `buf` here, but on the line 530 https://github.com/BOINC/boinc/pull/5123/files#diff-b710fcc072350b8bbb1bc13eb394da5cdbc0b0dfab019a93890ec10eadb41b86R530
we still read a chunk of 1024. And while this is generally won't fail, that could still mean that some data could be truncated and/or corrupted.
Please fix this.

File: sched/plan_class_spec.cpp [hunk 2]
```diff
@@ -1286,12 +1286,14 @@ int main() {
     }
 
     for (unsigned int i=0; i<pcs.classes.size(); i++) {
-        bool b = pcs.check(sreq, pcs.classes[i].name, hu);
+        WORKUNIT wu;
```
Comment (AenBleidd) [inline sched/plan_class_spec.cpp:1289]: I don't understand this change. It looks like not related to this particular PR at all.
Could you please specify why this is needed and why you set constant `100` values to `wu.id` and `wu.batch` ?

**Review by AenBleidd — CHANGES_REQUESTED** [review]

File: client/hostinfo_unix.cpp (hunk 1 above)
Comment (davidpanderson) [reply client/hostinfo_unix.cpp:488]: Good catch; I changed it to  sizeof(buf)

File: sched/plan_class_spec.cpp (hunk 2 above)
Comment (davidpanderson) [reply sched/plan_class_spec.cpp:1289]: This fixed a compile error; PLAN_CLASS_SPEC::check() now takes a final WORKUNIT arg,
and this code (test code, normally ifdef'd out) was missing it.

Comment (davidpanderson) [reply sched/plan_class_spec.cpp:1289]: The values (100) are so that you can test the plan class features related to WU ID and batch number.

**Review by AenBleidd — APPROVED** [review]

**Comment by bema-aei** [comment]
In the current version of the code (master branch), p_features size of the host record is still fixed 1024. That doesn't look right (and probably won't help):

    char p_features[1024];

https://github.com/BOINC/boinc/blob/master/db/boinc_db_types.h#L369

**Comment by bema-aei** [comment]
@davidpanderson @AenBleidd this probably isn't fixed yet.

**Comment by bema-aei** [comment]
@AenBleidd @davidpanderson does this omission in boinc_db_types affect the server only, or the client as well?

**Comment by AenBleidd** [comment]
@bema-aei, from what I see in the code, this is for the server only

**Comment by davidpanderson** [comment]
Server only.  Thanks for fixing this.
